---
- name: Ensure Firewall is installed
  apt:
    name: ufw
    state: present
    
- name: Install Curl for Validation
  apt:
    name: curl
    state: present
    
- name: Creating a new firewall rule and blocking it
  ufw:
    rule: deny
    from: 192.168.56.129

- name: Reload Firewall
  shell: sudo ufw reload
