---
- name: Ensure Firewall is installed
  apt:
    name: ufw
    state: present
    
- name: Install Curl for Validation
  apt:
    name: curl
    state: present
      
- name: Delete the Firewall rule
  shell: sudo ufw delete deny from 192.168.56.129

- name: Reload Firewall
  shell: sudo ufw reload
